"""Add interface information models

Revision ID: 7cc0f7c99bd8
Revises: c565f6e0902f
Create Date: 2025-11-06 09:10:09.765440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc0f7c99bd8'
down_revision = 'c565f6e0902f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.String(length=40), nullable=True),
    sa.Column('documentation_url', sa.String(length=255), nullable=True),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('interface_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interface_endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('version_added', sa.String(length=50), nullable=True),
    sa.Column('version_removed', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoint_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['interface_endpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoint_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['interface_endpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endpoint_response')
    op.drop_table('endpoint_parameter')
    op.drop_table('interface_endpoint')
    op.drop_table('interface_change_log')
    op.drop_table('interface')
    # ### end Alembic commands ###
