"""Add interface

Revision ID: ec7a9028aab8
Revises: 7cc0f7c99bd8
Create Date: 2025-11-06 09:26:27.233252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7a9028aab8'
down_revision = '7cc0f7c99bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interface_hotkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('combo', sa.String(length=80), nullable=False),
    sa.Column('context', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interface_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interface', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supported_tasks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('mt_engines', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('languages_supported', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ui_routes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('resources', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interface', schema=None) as batch_op:
        batch_op.drop_column('resources')
        batch_op.drop_column('ui_routes')
        batch_op.drop_column('languages_supported')
        batch_op.drop_column('mt_engines')
        batch_op.drop_column('supported_tasks')

    op.drop_table('interface_workflow')
    op.drop_table('interface_hotkey')
    op.drop_table('interface_feature')
    # ### end Alembic commands ###
